name: Manual Release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Increment type: patch, minor, major or pre*'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Setup GIT
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Release
        run: 'npx release-it --increment ${{ github.event.inputs.increment }}'
